spring.application.name=delivery-ana
logging.level.org.springframework.security=DEBUG

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
application.jwt.secret-key=${JWT_SECRET}
application.jwt.expiration-ms=${JWT_EXPIRATION_MS}
application.jwt.refresh-token.expiration-days=${JWT_EXPIRATION_DAYS}

# SMS Provider Configuration

sms.provider.url=${SMS_API}
# Not sending real messages, just process by sms Provider and return report
sms.provider.debug=true
sms.provider.login=${SMS_LOGIN}
sms.provider.password=${SMS_PASSWORD}
sms.provider.sender=${SMS_SENDER_NAME}

# Default admin credentials
# CHANGE IN PRODUCTION

default.admin.phonenumber=${ADMIN_PHONENUMBER}
default.admin.password=${ADMIN_PASSWORD}

# Stripe api secret-key
payments.stripe.public-key=${STRIPE_PKEY}
payments.stripe.sercet-key=${STRIPE_SKEY}
